// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhacxhyjnrkrhbhrjcmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oYWN4aHlqbnJrcmhiaHJqY216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTM4NzIsImV4cCI6MjA2MTU2OTg3Mn0.ZWb1eTozqxCTDh8il0Dzwb4TCFY6xxFAKQeR1qoqeFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);